#ifndef STATUS_CODES_H
#define STATUS_CODES_H

enum STATUS {
    SUCCESS = 0,
    INVALID_COMMAND = 1,
    OPEN_SHAREFILE_CONNECTION = 2,
    OPEN_CONNECTION = 3,
    FILE_NOT_FOUND = 4,
    PERMISSION_DENIED = 5,
    UNKNOWN_ERROR = 6,
    CONNECTION_ERROR = 7,
    RECEIVER_NO_OPEN_CONNECTION = 8,
    REJECT_CONNECTION = 9
};

extern const char *STATUS_MESSAGES[];   

#endif